### PR TITLE
Ability to compile with ndk r10e

### LINKED ISSUE #76: Android NDK r10 support
Hi.
Did you plan to add supportof the NDK r10 with arm-linux-androideabi-4.8 toolchain?
With  NDK r10 with arm-linux-androideabi-4.8 toolchain I can't compile project:

CC      libavcodec/dcadec.o
CC      libavcodec/dcadsp.o
CC      libavcodec/dcaenc.o
CC      libavcodec/dct.o
libavcodec/dcaenc.c: In function 'encode_init':
libavcodec/dcaenc.c:228:36: warning: iteration 256u invokes undefined behavior [-Waggressive-loop-optimizations]
         lfe_fir_64i[i] = lfe_fir_64[i] * (1 << 25); //float -> int32_t
                                    ^
libavcodec/dcaenc.c:227:5: note: containing loop
     for (i = 0; i < 512; i++)
     ^
In file included from libavcodec/dcadec.c:49:0:
libavcodec/dcadec.c: In function 'dca_xbr_parse_frame':
libavcodec/arm/dca.h:36:5: error: can't find a register in class 'CORE_REGS' while reloading 'asm'
     __asm__ ("smmul   %8,  %14, %18           \n"
     ^
libavcodec/arm/dca.h:36:5: error: 'asm' operand has impossible constraints
libavcodec/dcadec.c:1884: confused by earlier errors, bailing out
make: *** [libavcodec/dcadec.o] Error 1
make: *** Waiting for unfinished jobs....

### PR DESCRIPTION
**Pull request by jacek-marchwicki**
Closes #76

### CODE REVIEW

**Comment by dzungpv** [comment]
I edit  build_android.sh replace arm-linux-androideabi-4.4.3 with arm-linux-androideabi-4.9 and r10e. Starting seem good but it stop at **arm-linux-androideabi-ld: ,noexecstack: unknown -z option**.
I build on Yosemite 10.10.3 and Xcode 6.3.1

```
INSTALL	libavutil/dict.h
INSTALL	libavutil/opt.h
INSTALL	libavutil/parseutils.h
INSTALL	libavutil/pixdesc.h
INSTALL	libavutil/pixfmt.h
INSTALL	libavutil/random_seed.h
INSTALL	libavutil/rational.h
INSTALL	libavutil/samplefmt.h
INSTALL	libavutil/sha.h
INSTALL	libavutil/time.h
INSTALL	libavutil/timecode.h
INSTALL	libavutil/timestamp.h
INSTALL	libavutil/version.h
INSTALL	libavutil/xtea.h
INSTALL	libavutil/avconfig.h
INSTALL	libavutil/libavutil.pc
AR	libavformat/libavformat.a
AR	libavresample/libavresample.a
AR	libavcodec/libavcodec.a
AR	libswresample/libswresample.a
AR	libswscale/libswscale.a
INSTALL	libavformat/libavformat.a
INSTALL	libavresample/libavresample.a
INSTALL	libswresample/libswresample.a
INSTALL	libswscale/libswscale.a
AR	libavutil/libavutil.a
INSTALL	libavutil/libavutil.a
INSTALL	libavcodec/libavcodec.a
/Users/dev/Library/Android/ndk-r10e/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-ld: ,noexecstack: unknown -z option
/Users/dev/Library/Android/ndk-r10e/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-ld: use the --help option for usage information
```

**Comment by jacek-marchwicki** [comment]
@dzungpv this is not enough - please look on this branch and this should work on mac, but still have some problem with linux (travis)

**Comment by dzungpv** [comment]
@jacek-marchwicki  Hope you can solve this, my app crash on android 5.1.1 with r8e.
I see this guy can build r10e successful, may be you want to see https://github.com/adfernandes/FFmpeg-AvRdft

**Comment by jacek-marchwicki** [comment]
@dzungpv this branch should work on linux and on mac but travis has some problems with building it so I can not merge

**Comment by dzungpv** [comment]
@jacek-marchwicki  I can build ./build_android.sh but build ndk lib failed:
```
Android NDK: ERROR:jni/Android.mk:ffmpeg-prebuilt: LOCAL_SRC_FILES points to a missing file    
Android NDK: Check that jni/ffmpeg-build/arm64-v8a/libffmpeg.so exists  or that its path is correct   
/Users/dev/Library/Android/ndk-r10e/build/core/prebuilt-library.mk:45: *** Android NDK: Aborting    .  Stop.
```
So maybe missing arm64-v8a and x86_64 setting.

**Comment by jacek-marchwicki** [comment]
@dzungpv set library-jni/jni/Application.mk
to: `APP_ABI := armeabi-v7a  armeabi x86`

**Comment by dzungpv** [comment]
@jacek-marchwicki Great work! I can build all now include android app.

I come here to find a ffmpeg project that I can customize and build, I am new to git submodule and ndk development too. How can I edit ffmpeg version from this project, example I want 2.6.1 version? And I want additional lib in .so with minimal size for some codec in my app which I can not download anywhere. This is not relate to this pull but I am very thank if you help me.

**Comment by jacek-marchwicki** [comment]
@dzungpv if this question does not refer to this pull request, put it to issue tracker
